package ru.nikidzawa.retroGameEngine.config;

public enum Color {
    NONE,              // 0
    WHITE,             // 1
    BLACK,             // 2
    RED,               // 3
    GREEN,             // 4
    BLUE,              // 5
    YELLOW,            // 6
    ORANGE,            // 7
    PURPLE,            // 8
    PINK,              // 9
    GRAY,              // 10
    BROWN,             // 11
    CYAN,              // 12
    MAGENTA,           // 13
    LIGHTGRAY,         // 14
    DARKGRAY,          // 15
    ALICEBLUE,         // 16
    AQUAMARINE,        // 17
    AZURE,             // 18
    BEIGE,             // 19
    BISQUE,            // 20
    BLANCHEDALMOND,    // 21
    BLUEVIOLET,        // 22
    CADETBLUE,         // 23
    CHARTREUSE,        // 24
    CHOCOLATE,         // 25
    CORAL,             // 26
    CORNSILK,          // 27
    CRIMSON,           // 28
    DARKOLIVEGREEN,    // 29
    DARKORANGE,        // 30
    DARKORCHID,        // 31
    DARKSEAGREEN,      // 32
    DARKSLATEBLUE,     // 33
    DARKSLATEGRAY,     // 34
    DARKTURQUOISE,     // 35
    DEEPPINK,          // 36
    DEEPSKYBLUE,       // 37
    DODGERBLUE,        // 38
    FIREBRICK,         // 39
    FLORALWHITE,       // 40
    FORESTGREEN,       // 41
    GAINSBORO,         // 42
    GOLD,              // 43
    GOLDENROD,         // 44
    HONEYDEW,          // 45
    HOTPINK,           // 46
    INDIANRED,         // 47
    IVORY,             // 48
    KHAKI,             // 49
    LAVENDER,          // 50
    LAVENDERBLUSH,     // 51
    LAWNGREEN,         // 52
    LEMONCHIFFON,      // 53
    LIGHTBLUE,         // 54
    LIGHTCORAL,        // 55
    LIGHTCYAN,         // 56
    LIGHTGOLDENRODYELLOW, // 57
    LIGHTGREEN,        // 58
    LIGHTPINK,         // 59
    LIGHTSEAGREEN,     // 60
    LIGHTSKYBLUE,      // 61
    LIGHTSLATEGRAY,    // 62
    LIGHTSTEELBLUE,    // 63
    LIGHTYELLOW,       // 64
    LIME,              // 65
    LIMEGREEN,         // 66
    LINEN,             // 67
    MEDIUMAQUAMARINE,  // 68
    MEDIUMBLUE,        // 69
    MEDIUMORCHID,      // 70
    MEDIUMPURPLE,      // 71
    MEDIUMSEAGREEN,    // 72
    MEDIUMSLATEBLUE,   // 73
    MEDIUMSPRINGGREEN, // 74
    MEDIUMTURQUOISE,   // 75
    MEDIUMVIOLETRED,   // 76
    MIDNIGHTBLUE,      // 77
    MINTCREAM,         // 78
    MISTYROSE,         // 79
    MOCCASIN,          // 80
    NAVAJOWHITE,       // 81
    OLDLACE,           // 82
    OLIVE,             // 83
    OLIVEDRAB,         // 84
    ORANGERED,         // 85
    ORCHID,            // 86
    PALEGOLDENROD,     // 87
    PALEGREEN,         // 88
    PALETURQUOISE,     // 89
    PALEVIOLETRED,     // 90
    PAPAYAWHIP,        // 91
    PEACHPUFF,         // 92
    PERU,              // 93
    PLUM,              // 94
    POWDERBLUE,        // 95
    ROSYBROWN,         // 96
    ROYALBLUE,         // 97
    SADDLEBROWN,       // 98
    SALMON,            // 99
    SANDYBROWN,        // 100
    SEAGREEN,          // 101
    SEASHELL,          // 102
    SIENNA,            // 103
    SILVER,            // 104
    SKYBLUE,           // 105
    SLATEBLUE,         // 106
    SLATEGRAY,         // 107
    SNOW,              // 108
    SPRINGGREEN,       // 109
    STEELBLUE,         // 110
    TAN,               // 111
    TEAL,              // 112
    THISTLE,           // 113
    TOMATO,            // 114
    TRANSPARENT,       // 115
    TURQUOISE,         // 116
    VIOLET,            // 117
    WHEAT,             // 118
    WHITESMOKE,        // 119
    YELLOWGREEN        // 120
}
